# Generated by Django 4.0.5 on 2022-07-07 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_employee_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='shift',
            field=models.CharField(choices=[('zero', '0'), ('one', '1'), ('two', '2'), ('three', '3'), ('four', '4')], default='1', max_length=6),
        ),
    ]
