# Generated by Django 4.0.5 on 2022-07-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('date', models.CharField(max_length=15)),
                ('slip_no', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('party_name', models.CharField(max_length=200)),
                ('item', models.CharField(max_length=10)),
                ('litre', models.CharField(max_length=10)),
                ('amt', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Partyname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_name', models.CharField(max_length=200)),
            ],
        ),
    ]
